groups:
  - name: misacash
    rules:
      # Alertas de Sistema
      - alert: HighCPUUsage
        expr: avg(rate(process_cpu_seconds_total[5m])) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Uso de CPU alto"
          description: "O uso de CPU está acima de 80% por 5 minutos"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Uso de memória alto"
          description: "O uso de memória está acima de 85% por 5 minutos"

      - alert: HighDiskUsage
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes * 100 > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Uso de disco alto"
          description: "O uso de disco está acima de 90% por 5 minutos"

      # Alertas de Aplicação
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100 > 5
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Taxa de erro alta"
          description: "A taxa de erros HTTP 5xx está acima de 5% por 5 minutos"

      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Latência alta"
          description: "O percentil 95 da latência está acima de 1 segundo por 5 minutos"

      - alert: HighRequestRate
        expr: rate(http_requests_total[5m]) > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Taxa de requisições alta"
          description: "A taxa de requisições está acima de 1000 por minuto por 5 minutos"

      # Alertas de Banco de Dados
      - alert: HighDBConnections
        expr: pg_stat_activity_count > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Muitas conexões com o banco"
          description: "O número de conexões com o banco está acima de 100 por 5 minutos"

      - alert: SlowDBQueries
        expr: rate(pg_stat_activity_max_tx_duration{datname="misacash"}[5m]) > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Queries lentas"
          description: "Existem queries executando por mais de 10 segundos"

      # Alertas de Cache
      - alert: HighCacheMissRate
        expr: rate(cache_misses_total[5m]) / rate(cache_hits_total[5m]) * 100 > 20
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Taxa de cache miss alta"
          description: "A taxa de cache miss está acima de 20% por 5 minutos"

      # Alertas de Segurança
      - alert: HighAuthFailureRate
        expr: rate(http_requests_total{status="401"}[5m]) / rate(http_requests_total[5m]) * 100 > 10
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Taxa de falha de autenticação alta"
          description: "A taxa de falhas de autenticação está acima de 10% por 5 minutos"

      - alert: HighRateLimitExceeded
        expr: rate(http_requests_total{status="429"}[5m]) > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Muitas requisições bloqueadas"
          description: "Muitas requisições estão sendo bloqueadas por rate limit"

      # Alertas de Frontend
      - alert: HighFrontendErrorRate
        expr: rate(frontend_errors_total[5m]) / rate(frontend_requests_total[5m]) * 100 > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Taxa de erro no frontend alta"
          description: "A taxa de erros no frontend está acima de 5% por 5 minutos"

      - alert: HighFrontendLatency
        expr: histogram_quantile(0.95, rate(frontend_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Latência no frontend alta"
          description: "O percentil 95 da latência no frontend está acima de 2 segundos" 